import Head from "next/head";
import Feed from "../components/Feed";
import Menu from "../components/Menu";
import Sidebar from "../components/Sidebar";
import { useSelector } from "react-redux";
import LightLoading from "../components/LightLoading";
import Layout from "../components/Layout";

export default function Home() {
  const loading = useSelector((state) => state.loading);
  return (
    <div>
      <Head>
        <title>Twitter DZ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {/* Feed */}
        <section className="w-full md:w-[600px] ml-20 md:ml-[250px] border-r-[1px] border-zinc-700">
          <Feed />
        </section>
      </Layout>
    </div>
  );
}
